on:
  release:
    types: [published]

name: Build on Release

jobs:
  build_mac_arm:
    name: Build | Mac ARM
    runs-on: macos-latest
    steps:
      - run: rustup target add aarch64-apple-darwin
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target aarch64-apple-darwin
      - run: mv target/aarch64-apple-darwin/release/site-monitor target/aarch64-apple-darwin/release/aarch64-apple-darwin-site-monitor
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/aarch64-apple-darwin/release/aarch64-apple-darwin-site-monitor
  build_mac_intel:
    name: Mac Intel
    runs-on: ubuntu-latest
    steps:
      - run: rustup target add x86_64-apple-darwin
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target x86_64-apple-darwin
      - run: mv target/x86_64-apple-darwin/release/site-monitor target/x86_64-apple-darwin/release/x86_64-apple-darwin-site-monitor
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/x86_64-apple-darwin/release/x86_64-apple-darwin-site-monitor
