on:
  - release
  - push

name: Build on Release

jobs:
  mac_arm:
    name: Mac ARM
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target aarch64-apple-darwin
  mac_intel:
    name: Mac Intel
    runs-on: macos-latest
    steps:
      - run: rustup target add x86_64-apple-darwin
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target x86_64-apple-darwin
